// Parámetros de configuración
export const Configurations = {
  SCORE_PASSWORD: 3, // NIVEL MÍNIMO DE CALIFICACIÓN PASSWORD
  SALT_ROUNDS: 10, // NUMERO DE SALTOS PARA GENERACIÓN DE HASH
  WRONG_LOGIN_LIMIT: 3, // NUMERO MÁXIMO DE INTENTOS DE INICIO DE SESIÓN ERRONEOS
  MINUTES_LOGIN_LOCK: 15, // TIEMPO EN MINUTOS DE BLOQUEO DE CUENTA
  // LISTA DE DOMINIOS DE EMAIL NO PERMITIDOS
  BLACK_LIST_EMAILS: [
    '10minutemail.com',
    'fremont.nodebalancer.linode.com',
    'yopmail.com',
    'cool.fr.nf',
    'jetable.fr.nf',
    'nospam.ze.tc',
    'nomail.xl.cx',
    'mega.zik.dj',
    'speed.1s.fr',
    'courriel.fr.nf',
    'moncourrier.fr.nf',
    'monemail.fr.nf',
    'monmail.fr.nf',
    'mailinator',
    'binkmail.com',
    'bobmail.info',
    'chammy.info',
    'devnullmail.com',
    'letthemeatspam.com',
    'mailinator.com',
    'mailinater.com',
    'mailinator.net',
    'mailinator2.com',
    'notmailinator.com',
    'reallymymail.com',
    'reconmail.com',
    'safetymail.info',
    'sendspamhere.com',
    'sogetthis.com',
    'spambooger.com',
    'spamherelots.com',
    'spamhereplease.com',
    'spamthisplease.com',
    'streetwisemail.com',
    'suremail.info',
    'thisisnotmyrealemail.com',
    'tradermail.info',
    'veryrealemail.com',
    'zippymail.info',
    'guerrillamail',
    'maildrop',
    'mailnesia',
    'worldmagic.ink',
    'gufum.com',
    'mail.com',
    'theeyeoftruth.com',
    'bmomento.com',
    'bixolabs.com',
    'evildrako654.online',
    'mailtemporal.net',
  ],
}
